-- CreateTable
CREATE TABLE "ORDENCOMPRAHISTORIALESTADO" (
    "id_historial" SERIAL NOT NULL,
    "estado_anterior" "EstadoOrdenCompra" NOT NULL,
    "estado_nuevo" "EstadoOrdenCompra" NOT NULL,
    "observacion" TEXT,
    "fecha" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FK_orden_compra" INTEGER NOT NULL,
    "FK_usuario" INTEGER NOT NULL,

    CONSTRAINT "ORDENCOMPRAHISTORIALESTADO_pkey" PRIMARY KEY ("id_historial")
);

-- CreateIndex
CREATE INDEX "ORDENCOMPRAHISTORIALESTADO_FK_orden_compra_idx" ON "ORDENCOMPRAHISTORIALESTADO"("FK_orden_compra");

-- AddForeignKey
ALTER TABLE "ORDENCOMPRAHISTORIALESTADO" ADD CONSTRAINT "ORDENCOMPRAHISTORIALESTADO_FK_orden_compra_fkey" FOREIGN KEY ("FK_orden_compra") REFERENCES "ORDENCOMPRA"("id_orden_compra") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDENCOMPRAHISTORIALESTADO" ADD CONSTRAINT "ORDENCOMPRAHISTORIALESTADO_FK_usuario_fkey" FOREIGN KEY ("FK_usuario") REFERENCES "USUARIO"("id_usuario") ON DELETE RESTRICT ON UPDATE CASCADE;
